DROP TABLE specjalizacje;
DROP TABLE zabiegi;
DROP TABLE szczepienia;
DROP TABLE zdjecia;
DROP TABLE weterynarze;
DROP TABLE adopcje;
DROP TABLE adoptujacy;
DROP TABLE zwierzeta;
DROP TABLE pomieszczenia;
DROP TABLE opinie;
DROP TABLE pracownicy;
DROP TABLE wolontariusze;
DROP TABLE zasoby;
DROP TABLE schroniska;


CREATE TABLE schroniska (
    id_schroniska INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT schroniska_pk PRIMARY KEY,
    nazwa VARCHAR(512) NOT NULL,
    adres VARCHAR(512) NOT NULL,
    telefon VARCHAR(9) NOT NULL,
    email VARCHAR(256) NOT NULL,
    CONSTRAINT ck_telefon_schr CHECK (REGEXP_LIKE(telefon, '^[0-9]{9}$'))
);

CREATE TABLE pomieszczenia (
    id_pomieszczenia INTEGER
        CONSTRAINT pomieszczenia_pk PRIMARY KEY,
    typ VARCHAR(256) NOT NULL,
    budynek VARCHAR(256) NOT NULL,
    ilosc_kojcy INTEGER NOT NULL,
    id_schroniska INTEGER NOT NULL,
    CONSTRAINT pomieszczenia_schroniska_fk FOREIGN KEY (id_schroniska) REFERENCES schroniska (id_schroniska)
);

CREATE TABLE opinie (
    id_opinii INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT opinie_pk PRIMARY KEY,
    tresc VARCHAR(2048) NOT NULL,
    DATA DATE NOT NULL,
    id_schroniska INTEGER NOT NULL,
    CONSTRAINT opinie_schroniska_fk FOREIGN KEY (id_schroniska) REFERENCES schroniska (id_schroniska)
);

CREATE TABLE pracownicy (
    pesel VARCHAR(11) 
        CONSTRAINT pracownicy_pk PRIMARY KEY,
    imie VARCHAR(256) NOT NULL,
    nazwisko VARCHAR(256) NOT NULL,
    etat VARCHAR(256) NOT NULL,
    wynagrodzenie NUMBER NOT NULL,
    data_ur DATE NOT NULL,
    data_zatr DATE NOT NULL,
    telefon VARCHAR(9) NOT NULL,
    id_schroniska INTEGER NOT NULL,
    CONSTRAINT pracownicy_schroniska_fk FOREIGN KEY (id_schroniska) REFERENCES schroniska (id_schroniska),
    CONSTRAINT ck_etat CHECK (etat IN ('dyrektor', 'opiekun', 'administracja')),
    CONSTRAINT ck_wynagrodzenie CHECK (wynagrodzenie >= 0),
    CONSTRAINT ck_telefon_prac CHECK (REGEXP_LIKE(telefon, '^[0-9]{9}$')),
    CONSTRAINT ck_pesel_prac CHECK (REGEXP_LIKE(pesel, '^[0-9]{11}$'))
);

CREATE TABLE zasoby (
    id_zasobu INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT zasoby_pk PRIMARY KEY,
    typ VARCHAR(256) NOT NULL,
    nazwa VARCHAR(256) NOT NULL,
    ilosc INTEGER NOT NULL,
    id_schroniska INTEGER NOT NULL,
    CONSTRAINT zasoby_schroniska_fk FOREIGN KEY (id_schroniska) REFERENCES schroniska (id_schroniska),
    CONSTRAINT ck_ilosc CHECK (ilosc >= 0)
);

CREATE TABLE wolontariusze (
    pesel VARCHAR(11) CONSTRAINT wolontariusze_pk PRIMARY KEY,
    imie VARCHAR(256) NOT NULL,
    nazwisko VARCHAR(256) NOT NULL,
    data_ur DATE NOT NULL,
    telefon VARCHAR(9) NOT NULL,
    id_schroniska INTEGER NOT NULL,
    CONSTRAINT wolontariusze_schroniska_fk FOREIGN KEY (id_schroniska) REFERENCES schroniska (id_schroniska),
    CONSTRAINT ck_telefon_wol CHECK (REGEXP_LIKE(telefon, '^[0-9]{9}$')),
    CONSTRAINT ck_pesel_wol CHECK (REGEXP_LIKE(pesel, '^[0-9]{11}$'))
);

CREATE TABLE zwierzeta (
    id_zwierz INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT zwierzeta_pk PRIMARY KEY,
    imie VARCHAR(256) NOT NULL,
    gatunek VARCHAR(256) NOT NULL,
    data_ur DATE NOT NULL,
    id_pomieszczenia INTEGER NOT NULL,
    CONSTRAINT zwierzeta_pomieszczenia_fk FOREIGN KEY (id_pomieszczenia) REFERENCES pomieszczenia (id_pomieszczenia)
);

CREATE TABLE szczepienia (
    id_szczep INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT szczepienia_pk PRIMARY KEY,
    choroba VARCHAR(2048) NOT NULL,
    status VARCHAR(1) NOT NULL,
    id_zwierz INTEGER NOT NULL,
    CONSTRAINT szczepienia_zwierzeta_fk FOREIGN KEY (id_zwierz) REFERENCES zwierzeta (id_zwierz)
);

CREATE TABLE zdjecia (
    id_zdjecia INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT zdjecia_pk PRIMARY KEY,
    sciezka VARCHAR(256),
    id_zwierz INTEGER NOT NULL,
    CONSTRAINT zdjecia_zwierzeta_fk FOREIGN KEY (id_zwierz) REFERENCES zwierzeta (id_zwierz)
);

CREATE TABLE weterynarze (
    id_wet INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT id_wet_pk PRIMARY KEY,
    imie VARCHAR(256) NOT NULL,
    nazwisko VARCHAR(256) NOT NULL,
	adres VARCHAR(256) NOT NULL,
	telefon VARCHAR(9) NOT NULL,
	klinika VARCHAR(256) NOT NULL,
	CONSTRAINT ck_telefon_wet CHECK (REGEXP_LIKE(telefon, '^[0-9]{9}$'))
);

CREATE TABLE zabiegi (
    id_zabiegu INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT zabiegi_pk PRIMARY KEY,
    DATA DATE NOT NULL,
    status VARCHAR(1) NOT NULL,
    opis VARCHAR(256),
    id_zwierz INTEGER NOT NULL,
    id_wet INTEGER NOT NULL,
    CONSTRAINT zabiegi_weterynarze_fk FOREIGN KEY (id_wet) REFERENCES weterynarze (id_wet),
    CONSTRAINT zabiegi_zwierzeta_fk FOREIGN KEY (id_zwierz) REFERENCES zwierzeta (id_zwierz)
);

CREATE TABLE specjalizacje (
    id_wet INTEGER NOT NULL,
    gatunek VARCHAR(50) NOT NULL,
    CONSTRAINT specjalizacje_pk PRIMARY KEY (id_wet, gatunek),
    CONSTRAINT weterynarze_fk FOREIGN KEY (id_wet) REFERENCES weterynarze(id_wet)
);

CREATE TABLE adoptujacy (
    pesel VARCHAR(11) CONSTRAINT pesel_pk PRIMARY KEY,
    imie VARCHAR(256) NOT NULL,
    nazwisko VARCHAR(256) NOT NULL,
	data_ur DATE NOT NULL,
	telefon VARCHAR(9) NOT NULL,
	CONSTRAINT ck_pesel_adopt CHECK (REGEXP_LIKE(pesel, '^[0-9]{11}$')),
	CONSTRAINT ck_telefon_adopt CHECK (REGEXP_LIKE(telefon, '^[0-9]{9}$'))
);

CREATE TABLE adopcje (
    id_adopcji INTEGER 
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    DATA DATE NULL,
    status VARCHAR(256) NOT NULL,
	pesel VARCHAR(11) NULL,
	id_zwierz INTEGER NOT NULL,
	CONSTRAINT adoptujacy_fk FOREIGN KEY(pesel) REFERENCES adoptujacy(pesel),
	CONSTRAINT zwierzeta_fk FOREIGN KEY(id_zwierz) REFERENCES zwierzeta(id_zwierz),
	CONSTRAINT ck_pesel_adopcje CHECK (REGEXP_LIKE(pesel, '^[0-9]{11}$'))
);


--Sekwencje i triggery

DROP SEQUENCE seq_pomieszczenia;
CREATE SEQUENCE seq_pomieszczenia START WITH 10 INCREMENT BY 10;

CREATE OR REPLACE TRIGGER trg_pomieszczenia_pk
BEFORE INSERT ON pomieszczenia
FOR EACH ROW
BEGIN
    IF :NEW.id_pomieszczenia IS NULL THEN
        :NEW.id_pomieszczenia := seq_pomieszczenia.NEXTVAL;
    END IF;
END;
/

-- Funkcja - zaklada ze zwierze mozna adoptowac gdy jest szczepione i nie ma niezakończonych zabiegow

CREATE OR REPLACE FUNCTION czy_do_adopcji(p_id_zwierz NUMBER) 
RETURN VARCHAR2
IS
    v_zabiegi NUMBER;
    v_szczepienia NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_zabiegi
    FROM zabiegi
    WHERE id_zwierz = p_id_zwierz AND status = 'N'; -- N = niezakończony

    SELECT COUNT(*) INTO v_szczepienia
    FROM szczepienia
    WHERE id_zwierz = p_id_zwierz AND status = 'T'; -- T = tak

    IF v_zabiegi > 0 THEN
        RETURN 'NIE - trwające zabiegi';
    ELSIF v_szczepienia = 0 THEN
        RETURN 'NIE - brak szczepień';
    ELSE
        RETURN 'TAK';
    END IF;
END;
/

--Procedura dodaje nowe zwierze

CREATE OR REPLACE PROCEDURE dodaj_zwierze(
    p_imie          IN VARCHAR2,
    p_gatunek       IN VARCHAR2,
    p_data_ur       IN DATE,
    p_id_pomieszczenia IN NUMBER,
    p_zdj_sciezka   IN VARCHAR2,
    p_id_out        OUT NUMBER
)
IS
BEGIN
    INSERT INTO zwierzeta(imie, gatunek, data_ur, id_pomieszczenia)
    VALUES (p_imie, p_gatunek, p_data_ur, p_id_pomieszczenia)
    RETURNING id_zwierz INTO p_id_out;
    
    INSERT INTO zdjecia(sciezka, id_zwierz)
    VALUES (p_zdj_sciezka, p_id_out);
    
    INSERT INTO adopcje(status, pesel, id_zwierz)
    VALUES ('N', NULL, p_id_out);
END;
/

-- procedura przeprowadza adopcje

CREATE OR REPLACE PROCEDURE zakoncz_adopcje(
    p_id_adopcji IN NUMBER,
    p_pesel      IN VARCHAR2,
    p_msg        OUT VARCHAR2
)
IS
    v_id_zwierz   NUMBER;


    v_czy_moze    VARCHAR2(200);
    v_istnieje    NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_istnieje FROM adopcje WHERE id_adopcji = p_id_adopcji;
    IF v_istnieje = 0 THEN
        p_msg := 'Podana adopcja nie istnieje.';
        RETURN;
    END IF;

    SELECT id_zwierz INTO v_id_zwierz FROM adopcje WHERE id_adopcji = p_id_adopcji;
    v_czy_moze := czy_do_adopcji(v_id_zwierz);

    IF v_czy_moze LIKE 'NIE%' THEN
        p_msg := 'Adopcja odrzucona. Powód: ' || v_czy_moze;
        RETURN;
    END IF;

    SELECT COUNT(*) INTO v_istnieje FROM adoptujacy WHERE pesel = p_pesel;
    IF v_istnieje = 0 THEN
        p_msg := 'Podany adoptujący nie istnieje.';
        RETURN;
    END IF;

    UPDATE adopcje
    SET status = 'Z', pesel = p_pesel, data = SYSDATE
    WHERE id_adopcji = p_id_adopcji;
    p_msg := 'Zwierze zostało zaadoptowane.';
END;
/
