DROP TABLE CONSTRAINT_LOOKUP;

CREATE TABLE CONSTRAINT_LOOKUP (
    id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT constraint_lookup_pk PRIMARY KEY,
    constraint_name VARCHAR2(512),
    message VARCHAR2(512)
);

INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_ETAT',             'Etat musi zawierać się w: dyrektor, opiekun, administracja.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_WYNAGRODZENIE',    'Wynagrodzenie nie może być ujemne.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_TELEFON_SCHR',     'Numer telefonu musi składać się z dokładnie 9 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_TELEFON_PRAC',     'Numer telefonu musi składać się z dokładnie 9 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_TELEFON_WOL',      'Numer telefonu musi składać się z dokładnie 9 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_TELEFON_WET',      'Numer telefonu musi składać się z dokładnie 9 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_TELEFON_ADOPT',    'Numer telefonu musi składać się z dokładnie 9 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_PESEL_PRAC',       'PESEL musi mieć 11 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_PESEL_WOL',        'PESEL musi mieć 11 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_PESEL_ADOPCJE',    'PESEL musi mieć 11 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_PESEL_ADOPT',      'PESEL musi mieć 11 cyfr.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('CK_ILOSC',            'Ilość zasobów nie może być ujemna.');

INSERT INTO constraint_lookup (constraint_name, message) VALUES ('ZWIERZETA_POMIESZCZENIA_FK',  'Wybrane pomieszczenie nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('POMIESZCZENIA_SCHRONISKA_FK', 'Wybrane schronisko nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('OPINIE_SCHRONISKA_FK',        'Wybrane schronisko nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('PRACOWNICY_SCHRONISKA_FK',    'Wybrane schronisko nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('ZASOBY_SCHRONISKA_FK',        'Wybrane schronisko nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('WOLONTARIUSZE_SCHRONISKA_FK', 'Wybrane schronisko nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('SZCZEPIENIA_ZWIERZETA_FK',    'Wybrane zwierzę nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('ZDJECIA_ZWIERZETA_FK',        'Wybrane zwierzę nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('ZABIEGI_ZWIERZETA_FK',        'Wybrane zwierzę nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('ZWIERZETA_FK',                'Wybrane zwierzę nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('ZABIEGI_WETERYNARZE_FK',      'Wybrany weterynarz nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('WETERYNARZE_FK',              'Wybrany weterynarz nie istnieje.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('ADOPTUJACY_FK',               'Wybrany adoptujący nie istnieje.');

INSERT INTO constraint_lookup (constraint_name, message) VALUES ('PRACOWNICY_PK',               'PESEL pracownika musi być unikalny.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('WOLONTARIUSZE_PK',            'PESEL wolontariusza musi być unikalny.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('PESEL_PK',                    'PESEL adoptującego musi być unikalny.');
INSERT INTO constraint_lookup (constraint_name, message) VALUES ('SPECJALIZACJE_PK',            'Weterynarz ma już taką specjalizację.');
